### ISSUE TITLE
useStyleSheet missing

### ISSUE THREAD

**Issue by ranglang** [atomicojs/hooks#1]
it seams that useStyleSheet can't be found in kit

**Comment by UpperCod** [comment]
Hi @ranglang , I apologize for this, I have solved this by adding this hook and another one that complements it `use-custom-property`, these hooks are available from version `@atomico/kit@0.3.1`

Links : 
1. [use-stylesheet](https://atomicojs.github.io/atomico-kit/use-stylesheet.html)
2. [use-custom-property](https://atomicojs.github.io/atomico-kit/use-custom-property.html)

I hope these hooks are useful to you

**Comment by ranglang** [comment]
Thank you, you are nice
