### ISSUE TITLE
Remove "workspaces" from package.json

### ISSUE THREAD

**Issue by efoken** [atomicojs/hooks#10]
We're getting warning from Yarn since a long long time about this. I think the "workspaces" field is not needed anyway in this project, because you only have one package and one package.json.

Yarn output:

```
warning Workspaces can only be enabled in private projects.
```

**Comment by UpperCod** [comment]
Hi @efoken , interesting, I didn't know that, I'm going to repair it, as soon as I have it ready I'll let you know.

By the way, have you tried the latest version of @atomico/storybook with storybook 7?
