### ISSUE TITLE
 The default export condition must come last

### ISSUE THREAD

**Issue by DamienCassou** [atomicojs/hooks#13]
When package.json is generated, the conditional exports are in the wrong order: ["default" must be the last one](https://nodejs.org/api/packages.html#packages_conditional_exports).

I reported the issue upstream in https://github.com/atomicojs/exports/issues/7.

**Comment by UpperCod** [comment]
Hi @DamienCassou Thank you for noticing this. Version 3.50.4 fixes this bug. I'll be attentive to anything you need. Greetings!

(The fix was for @atomico/exports.)
