### ISSUE TITLE
Add license to packages

### ISSUE THREAD

**Issue by mig8447** [atomicojs/hooks#16]
I see the license for Atomico in general is MIT, is it the same license for these packages? Could you add the license field on the packages?

**Comment by UpperCod** [comment]
Hi @mig8447 , thank you for reminding me. My goal is to ensure that all code related to the atomico package and its sub-packages under the @atomico organization must be open source under the MIT license. I overlooked this configuration in some repositories like this one. Now, in the attached release, all packages in this repository are released with the MIT license for NPM, and the license is also declared in the repository.

https://github.com/atomicojs/hooks/releases/tag/v4.1.2

If you find any repo of the organization without these changes, [let me know ](https://discord.gg/rZJr5hpps4) or if you generate a PR that references this, I will be happy to approve it.


Greetings

**Comment by mig8447** [comment]
Thank you for your quick reply

**Comment by mig8447** [comment]
Thank you for your quick reply, I consider this closed
